import {
    Lead,
    Contact,
    Deal,
    PipelineStage,
    N8NWorkflow,
    Activity,
    DashboardStats,
} from "./types";

// ─── LEADS ───
export const mockLeads: Lead[] = [
    {
        id: "lead-001",
        name: "Sarah Chen",
        email: "sarah.chen@techwave.io",
        company: "TechWave Solutions",
        role: "VP of Engineering",
        phone: "+1 (555) 234-5678",
        status: "qualified",
        source: "linkedin",
        score: 87,
        priority: "high",
        tags: ["enterprise", "saas", "hot-lead"],
        notes: "Interested in our automation suite. Has budget approved for Q1.",
        assignedTo: "You",
        createdAt: "2026-02-15T10:00:00Z",
        lastContactedAt: "2026-02-21T14:30:00Z",
    },
    {
        id: "lead-002",
        name: "Marcus Johnson",
        email: "m.johnson@growthly.com",
        company: "Growthly Inc.",
        role: "Head of Growth",
        phone: "+1 (555) 876-5432",
        status: "contacted",
        source: "cold_email",
        score: 62,
        priority: "medium",
        tags: ["startup", "growth"],
        notes: "Replied to cold email sequence #3. Wants a demo next week.",
        assignedTo: "You",
        createdAt: "2026-02-10T08:00:00Z",
        lastContactedAt: "2026-02-19T09:15:00Z",
    },
    {
        id: "lead-003",
        name: "Elena Vasquez",
        email: "elena@meridian.co",
        company: "Meridian Corp",
        role: "CEO",
        status: "new",
        source: "referral",
        score: 91,
        priority: "urgent",
        tags: ["enterprise", "decision-maker", "referral"],
        notes: "Referred by Michael Torres. Looking for full pipeline automation.",
        createdAt: "2026-02-22T16:00:00Z",
    },
    {
        id: "lead-004",
        name: "James O'Brien",
        email: "james@stackflow.dev",
        company: "StackFlow",
        role: "CTO",
        phone: "+44 20 7946 0958",
        status: "nurturing",
        source: "website",
        score: 45,
        priority: "low",
        tags: ["developer-tools", "small-team"],
        assignedTo: "You",
        createdAt: "2026-01-28T12:00:00Z",
        lastContactedAt: "2026-02-14T11:00:00Z",
    },
    {
        id: "lead-005",
        name: "Aisha Patel",
        email: "aisha@novahealth.com",
        company: "NovaHealth",
        role: "Director of Operations",
        phone: "+1 (555) 321-9876",
        status: "qualified",
        source: "paid_ads",
        score: 78,
        priority: "high",
        tags: ["healthcare", "enterprise", "compliance"],
        notes: "Needs HIPAA compliant solution. Budget discussion ongoing.",
        assignedTo: "You",
        createdAt: "2026-02-05T09:00:00Z",
        lastContactedAt: "2026-02-20T16:45:00Z",
    },
    {
        id: "lead-006",
        name: "David Kim",
        email: "dkim@orbitalai.com",
        company: "Orbital AI",
        role: "Product Manager",
        status: "contacted",
        source: "social_media",
        score: 55,
        priority: "medium",
        tags: ["ai", "saas"],
        createdAt: "2026-02-18T14:00:00Z",
        lastContactedAt: "2026-02-22T10:00:00Z",
    },
    {
        id: "lead-007",
        name: "Lisa Fernandez",
        email: "lisa@craftcommerce.io",
        company: "CraftCommerce",
        role: "Marketing Lead",
        status: "new",
        source: "n8n_flow",
        score: 72,
        priority: "medium",
        tags: ["e-commerce", "automation"],
        notes: "Captured via LinkedIn scraping flow. High engagement metrics.",
        createdAt: "2026-02-23T08:00:00Z",
    },
    {
        id: "lead-008",
        name: "Robert Zhang",
        email: "rzhang@finpulse.com",
        company: "FinPulse",
        role: "COO",
        phone: "+1 (555) 654-3210",
        status: "unqualified",
        source: "cold_email",
        score: 22,
        priority: "low",
        tags: ["fintech"],
        notes: "Not a fit — too small, no budget this year.",
        createdAt: "2026-02-01T10:00:00Z",
        lastContactedAt: "2026-02-08T13:00:00Z",
    },
    {
        id: "lead-009",
        name: "Anna Kowalski",
        email: "anna@brightspark.eu",
        company: "BrightSpark EU",
        role: "Head of Sales",
        phone: "+49 30 12345678",
        status: "qualified",
        source: "linkedin",
        score: 83,
        priority: "high",
        tags: ["europe", "enterprise", "saas"],
        notes: "Ready for proposal. Wants custom integration with their CRM.",
        assignedTo: "You",
        createdAt: "2026-02-12T07:00:00Z",
        lastContactedAt: "2026-02-22T15:30:00Z",
    },
    {
        id: "lead-010",
        name: "Tom Wilson",
        email: "twilson@cloudnest.io",
        company: "CloudNest",
        role: "Founder",
        status: "contacted",
        source: "referral",
        score: 68,
        priority: "medium",
        tags: ["startup", "cloud", "referral"],
        notes: "Interested but evaluating competitors. Follow up next week.",
        createdAt: "2026-02-16T11:00:00Z",
        lastContactedAt: "2026-02-21T09:00:00Z",
    },
];

// ─── CONTACTS ───
export const mockContacts: Contact[] = [
    {
        id: "contact-001",
        name: "Sarah Chen",
        email: "sarah.chen@techwave.io",
        company: "TechWave Solutions",
        role: "VP of Engineering",
        phone: "+1 (555) 234-5678",
        tags: ["enterprise", "decision-maker"],
        linkedLeadIds: ["lead-001"],
        createdAt: "2026-02-15T10:00:00Z",
        lastInteractionAt: "2026-02-21T14:30:00Z",
    },
    {
        id: "contact-002",
        name: "Marcus Johnson",
        email: "m.johnson@growthly.com",
        company: "Growthly Inc.",
        role: "Head of Growth",
        phone: "+1 (555) 876-5432",
        tags: ["startup"],
        linkedLeadIds: ["lead-002"],
        createdAt: "2026-02-10T08:00:00Z",
        lastInteractionAt: "2026-02-19T09:15:00Z",
    },
    {
        id: "contact-003",
        name: "Elena Vasquez",
        email: "elena@meridian.co",
        company: "Meridian Corp",
        role: "CEO",
        tags: ["enterprise", "c-suite"],
        linkedLeadIds: ["lead-003"],
        createdAt: "2026-02-22T16:00:00Z",
    },
    {
        id: "contact-004",
        name: "Anna Kowalski",
        email: "anna@brightspark.eu",
        company: "BrightSpark EU",
        role: "Head of Sales",
        phone: "+49 30 12345678",
        tags: ["europe", "enterprise"],
        linkedLeadIds: ["lead-009"],
        createdAt: "2026-02-12T07:00:00Z",
        lastInteractionAt: "2026-02-22T15:30:00Z",
    },
    {
        id: "contact-005",
        name: "Aisha Patel",
        email: "aisha@novahealth.com",
        company: "NovaHealth",
        role: "Director of Operations",
        phone: "+1 (555) 321-9876",
        tags: ["healthcare", "compliance"],
        linkedLeadIds: ["lead-005"],
        createdAt: "2026-02-05T09:00:00Z",
        lastInteractionAt: "2026-02-20T16:45:00Z",
    },
    {
        id: "contact-006",
        name: "Michael Torres",
        email: "mike@meridian.co",
        company: "Meridian Corp",
        role: "VP of Sales",
        phone: "+1 (555) 789-0123",
        tags: ["enterprise", "referral-source"],
        linkedLeadIds: [],
        createdAt: "2026-01-20T10:00:00Z",
        lastInteractionAt: "2026-02-22T12:00:00Z",
    },
];

// ─── DEALS ───
export const mockDeals: Deal[] = [
    {
        id: "deal-001",
        title: "TechWave Automation Suite",
        value: 48000,
        currency: "USD",
        stage: "proposal",
        probability: 65,
        contactId: "contact-001",
        contactName: "Sarah Chen",
        company: "TechWave Solutions",
        daysInStage: 4,
        expectedCloseDate: "2026-03-15",
        notes: "Proposal sent. Awaiting review from their engineering team.",
        createdAt: "2026-02-15T10:00:00Z",
    },
    {
        id: "deal-002",
        title: "Growthly Lead Gen Package",
        value: 12000,
        currency: "USD",
        stage: "qualified",
        probability: 40,
        contactId: "contact-002",
        contactName: "Marcus Johnson",
        company: "Growthly Inc.",
        daysInStage: 3,
        expectedCloseDate: "2026-04-01",
        notes: "Demo scheduled for next week.",
        createdAt: "2026-02-10T08:00:00Z",
    },
    {
        id: "deal-003",
        title: "Meridian Full Pipeline",
        value: 120000,
        currency: "USD",
        stage: "new",
        probability: 25,
        contactId: "contact-003",
        contactName: "Elena Vasquez",
        company: "Meridian Corp",
        daysInStage: 1,
        expectedCloseDate: "2026-05-01",
        notes: "High-value referral. Needs comprehensive solution.",
        createdAt: "2026-02-22T16:00:00Z",
    },
    {
        id: "deal-004",
        title: "BrightSpark Integration",
        value: 36000,
        currency: "USD",
        stage: "negotiation",
        probability: 80,
        contactId: "contact-004",
        contactName: "Anna Kowalski",
        company: "BrightSpark EU",
        daysInStage: 2,
        expectedCloseDate: "2026-03-01",
        notes: "Negotiating custom integration pricing. Almost there.",
        createdAt: "2026-02-12T07:00:00Z",
    },
    {
        id: "deal-005",
        title: "NovaHealth Compliance Suite",
        value: 85000,
        currency: "USD",
        stage: "proposal",
        probability: 55,
        contactId: "contact-005",
        contactName: "Aisha Patel",
        company: "NovaHealth",
        daysInStage: 6,
        expectedCloseDate: "2026-04-15",
        notes: "HIPAA requirements documented. Legal review in progress.",
        createdAt: "2026-02-05T09:00:00Z",
    },
    {
        id: "deal-006",
        title: "CloudNest Starter Package",
        value: 8500,
        currency: "USD",
        stage: "new",
        probability: 20,
        contactId: "contact-002",
        contactName: "Tom Wilson",
        company: "CloudNest",
        daysInStage: 5,
        expectedCloseDate: "2026-04-30",
        createdAt: "2026-02-16T11:00:00Z",
    },
    {
        id: "deal-007",
        title: "Meridian Phase 2 Training",
        value: 25000,
        currency: "USD",
        stage: "closed_won",
        probability: 100,
        contactId: "contact-006",
        contactName: "Michael Torres",
        company: "Meridian Corp",
        daysInStage: 0,
        expectedCloseDate: "2026-02-20",
        notes: "Closed! Upsell from initial engagement.",
        createdAt: "2026-01-20T10:00:00Z",
    },
];

// ─── PIPELINE STAGES ───
export const pipelineStages: PipelineStage[] = [
    {
        id: "new",
        label: "New",
        color: "var(--chart-1)",
        deals: mockDeals.filter((d) => d.stage === "new"),
    },
    {
        id: "qualified",
        label: "Qualified",
        color: "var(--chart-2)",
        deals: mockDeals.filter((d) => d.stage === "qualified"),
    },
    {
        id: "proposal",
        label: "Proposal",
        color: "var(--chart-3)",
        deals: mockDeals.filter((d) => d.stage === "proposal"),
    },
    {
        id: "negotiation",
        label: "Negotiation",
        color: "var(--chart-4)",
        deals: mockDeals.filter((d) => d.stage === "negotiation"),
    },
    {
        id: "closed_won",
        label: "Closed Won",
        color: "var(--chart-5)",
        deals: mockDeals.filter((d) => d.stage === "closed_won"),
    },
    {
        id: "closed_lost",
        label: "Closed Lost",
        color: "var(--destructive)",
        deals: mockDeals.filter((d) => d.stage === "closed_lost"),
    },
];

// ─── N8N WORKFLOWS ───
export const mockWorkflows: N8NWorkflow[] = [
    {
        id: "wf-001",
        name: "LinkedIn Lead Scraper",
        description:
            "Scrapes LinkedIn Sales Navigator for leads matching ICP criteria and adds them to the CRM.",
        status: "active",
        webhookUrl: "https://n8n.pixl.dev/webhook/linkedin-scraper",
        lastExecutedAt: "2026-02-23T07:00:00Z",
        executionCount: 342,
        errorCount: 3,
        tags: ["linkedin", "lead-gen", "scraping"],
        createdAt: "2026-01-15T10:00:00Z",
    },
    {
        id: "wf-002",
        name: "Cold Email Sequence",
        description:
            "4-step cold email drip campaign with follow-up triggers based on open/click events.",
        status: "active",
        webhookUrl: "https://n8n.pixl.dev/webhook/cold-email",
        lastExecutedAt: "2026-02-23T06:30:00Z",
        executionCount: 1289,
        errorCount: 12,
        tags: ["email", "outreach", "drip"],
        createdAt: "2026-01-10T08:00:00Z",
    },
    {
        id: "wf-003",
        name: "Lead Scoring Engine",
        description:
            "Automatically scores leads based on engagement, company size, and ICP fit using AI classification.",
        status: "active",
        webhookUrl: "https://n8n.pixl.dev/webhook/lead-scoring",
        lastExecutedAt: "2026-02-23T08:00:00Z",
        executionCount: 856,
        errorCount: 0,
        tags: ["scoring", "ai", "automation"],
        createdAt: "2026-01-20T12:00:00Z",
    },
    {
        id: "wf-004",
        name: "Meeting Scheduler Bot",
        description:
            "Sends Calendly links to qualified leads and syncs meeting bookings back to the CRM.",
        status: "inactive",
        webhookUrl: "https://n8n.pixl.dev/webhook/meeting-scheduler",
        lastExecutedAt: "2026-02-18T14:00:00Z",
        executionCount: 94,
        errorCount: 1,
        tags: ["scheduling", "calendly"],
        createdAt: "2026-02-01T09:00:00Z",
    },
    {
        id: "wf-005",
        name: "Deal Stage Notifier",
        description:
            "Sends Slack notifications and updates dashboards when deals move between pipeline stages.",
        status: "error",
        webhookUrl: "https://n8n.pixl.dev/webhook/deal-notify",
        lastExecutedAt: "2026-02-22T20:00:00Z",
        executionCount: 215,
        errorCount: 28,
        tags: ["notifications", "slack", "pipeline"],
        createdAt: "2026-01-25T11:00:00Z",
    },
    {
        id: "wf-006",
        name: "Website Visitor Tracker",
        description:
            "Captures website visitor data, enriches it with company info, and creates leads for high-intent visitors.",
        status: "active",
        webhookUrl: "https://n8n.pixl.dev/webhook/visitor-tracker",
        lastExecutedAt: "2026-02-23T09:00:00Z",
        executionCount: 2103,
        errorCount: 5,
        tags: ["website", "tracking", "enrichment"],
        createdAt: "2026-01-05T14:00:00Z",
    },
];

// ─── ACTIVITIES ───
export const mockActivities: Activity[] = [
    {
        id: "act-001",
        type: "lead_created",
        title: "New lead captured",
        description: "Lisa Fernandez from CraftCommerce was captured via LinkedIn scraping flow.",
        entityId: "lead-007",
        entityType: "lead",
        entityName: "Lisa Fernandez",
        createdAt: "2026-02-23T08:00:00Z",
    },
    {
        id: "act-002",
        type: "deal_moved",
        title: "Deal moved to Negotiation",
        description: "BrightSpark Integration deal moved from Proposal to Negotiation stage.",
        entityId: "deal-004",
        entityType: "deal",
        entityName: "BrightSpark Integration",
        createdAt: "2026-02-22T15:30:00Z",
    },
    {
        id: "act-003",
        type: "email",
        title: "Follow-up email sent",
        description: "Sent proposal follow-up to Sarah Chen at TechWave Solutions.",
        entityId: "contact-001",
        entityType: "contact",
        entityName: "Sarah Chen",
        createdAt: "2026-02-22T14:00:00Z",
    },
    {
        id: "act-004",
        type: "workflow_triggered",
        title: "Lead scoring completed",
        description: "Lead Scoring Engine processed 12 new leads. Average score: 64.",
        entityId: "wf-003",
        entityType: "workflow",
        entityName: "Lead Scoring Engine",
        createdAt: "2026-02-22T12:00:00Z",
    },
    {
        id: "act-005",
        type: "meeting",
        title: "Discovery call booked",
        description: "Elena Vasquez (Meridian Corp) booked a 30-min discovery call for Feb 25.",
        entityId: "contact-003",
        entityType: "contact",
        entityName: "Elena Vasquez",
        createdAt: "2026-02-22T10:30:00Z",
    },
    {
        id: "act-006",
        type: "call",
        title: "Sales call completed",
        description: "45-min call with Anna Kowalski. Discussed pricing for custom integration.",
        entityId: "contact-004",
        entityType: "contact",
        entityName: "Anna Kowalski",
        createdAt: "2026-02-21T16:00:00Z",
    },
    {
        id: "act-007",
        type: "note",
        title: "Qualification note added",
        description: "David Kim at Orbital AI is evaluating 3 tools. Decision expected by March.",
        entityId: "lead-006",
        entityType: "lead",
        entityName: "David Kim",
        createdAt: "2026-02-21T14:00:00Z",
    },
    {
        id: "act-008",
        type: "task",
        title: "Follow-up reminder",
        description: "Reminder: Follow up with Tom Wilson at CloudNest about competitor comparison.",
        entityId: "lead-010",
        entityType: "lead",
        entityName: "Tom Wilson",
        createdAt: "2026-02-21T09:00:00Z",
    },
];

// ─── DASHBOARD STATS ───
export const mockDashboardStats: DashboardStats = {
    totalLeads: 247,
    newLeadsThisWeek: 18,
    conversionRate: 23.4,
    conversionRateChange: 2.1,
    revenuePipeline: 334500,
    revenuePipelineChange: 12.5,
    activeWorkflows: 4,
    dealsClosedThisMonth: 3,
};
